version: "3"
services:
  app:
    container_name: desafio-plub-docker
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - "9090:9090"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
